spring:
  datasource:
    url: jdbc:mysql:///shop1901
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 47.112.140.174
    port: 5672
    virtual-host: /
dubbo:
  protocol:
    name: dubbo
    port: -1
  application:
    name: service_goods
  registry:
    address: zookeeper://47.112.140.174:2181